- lib/req.ex
Thought it was a strange API, and then wondered why the strange API didn't work. Turns out it was just a small typo in the docs 😄
Thanks for this library!
> Fix typo in docs

- README.md
I believe the field name is now `uri` (per https://github.com/wojtekmach/req/blob/b397a0aad1e8314350b222aa04a81cc4e1e2f24b/lib/req/request.ex#L9).
> Update readme (request.uri)

- lib/req/response.ex
It was possible to annotate Requests with library-specific metadata using the :private field, however the same wasn't true for Responses. This means that it wasn't possible to return extra information to the caller.
> Add `:private` field to Response

- lib/req.ex
- lib/req/response.ex
> Add initial type specs

- README.md
- lib/req/request.ex
- lib/req/steps.ex
- test/req/steps_test.exs
> `follow_redirects`: Don't send auth headers on redirect to different host

- README.md
- lib/req/steps.ex
- test/req/steps_test.exs
Closes #52 and closes #60. This version gets rid of the `load_rtc` step. It uses similar logic under the hood, with the following changes:
1. Look for `login` instead of `username`
2. Parse records stored in `.netrc` as a single line or as multiple lines
> Replace load_netrc with auth: :netrc | {:netrc, path}

- lib/req/steps.ex
- test/httpbin_test.exs
- test/my_netrc
- test/test_helper.exs
I thought it might be beneficial to be able to test the library against https://httpbin.org. As an added benefit this enables us to use doctests.
For now I implemented the tests for the
To not interfere with the existing tests and not depend on an internet connection (and a third-party service) I put those tests in an extra `test_httpbin` directory. To run those test just use
```
mix test test_httpbin
```
> add (first) httpbin.org tests

- lib/req/request.ex
- lib/req/steps.ex
- test/req/steps_test.exs
Closes #66.
Note that the option is added to `Req.build/3`, for a few reasons:
- the adapter runs like a request step, but it is really a required attribute of the request, unlike any other steps
- because the adapter is required and required to run last, it seemed confusing to make changes to something that is required as part of the process of adding defaults. It feels more natural to modify the request defaults when building the request.
I did not add new tests. I did update the two tests that use a custom adapter to add it using this option. Let me know if a separate test is desirable.
> add :adapter option

- lib/req/request.ex
- test/req/request_test.exs
Closes #69.
I wasn't sure if `prepare/1` should be required to handle a halted request. It doesn't appear to me that a pipeline can be halted before all of the request steps have run, so I didn't handle it for now.
> Add Req.Request.prepare/1

- README.md
- lib/req.ex
- lib/req/steps.ex
- test/req/steps_test.exs
Closes #25.
I took liberties with the name as I thought `compress_request` was clearer.
I could not come up with a good example for the docs without using `prepare/1`. Unfortunately compressed requests to [httpbin.org are not decoded due to security risks](https://github.com/postmanlabs/httpbin/issues/577).
> add compress_request step

- lib/req/request.ex
Noticed this while reading through the new docs for the 0.3 release! If it's easier for you to just make this change yourself, please feel free to do so and close this PR. Cheers.
> Fix typo in Req.Request moduledoc

- lib/req.ex
Hi and thanks for creating this great library.
Was just curious if it would make sense to add none raising shorthands for `get`, `post`, `put`, `patch`, `delete` and `head`?
I wanted that for myself, so I thought it would make sense to share :blush:
> Add none raiseing shorthands

- lib/req/steps.ex
- test/req/steps_test.exs
Hi Wojtek! 👋
I'm not sure whether this would be the path to go, but just noticed that `json-api` responses don't call jason decode step because of the mime type, WDYT?
Cheers!
> Decode JSON when response is json-api mime type

- lib/req.ex
- lib/req/steps.ex
- test/req/steps_test.exs
Hello,
I am using your package for a project of mine and it works very well. But at some point I had to use a proxy and I realized that I could not pass a `:proxy` option directly to the request function call.
I really needed this feature, so I added a `:proxy` option that the user can pass along with `:timeout` and `:protocol`. The proxy must be provided in a format supported by the [Mint](https://github.com/elixir-mint/mint) package: A tuple `{scheme, address, port, opts}` that identifies the proxy to connect to. 
```elixir
https_proxy = {:https, "34.91.135.38", 80, []}
req = Req.get!("https://api.github.com/repos/sneako/finch", proxy: https_proxy)
```
Also note that I did not implement any extra tests after I added this feature. That's because I assume this is not a significant change …
> Add proxy to connection options

- lib/req.ex
The `@external_resource` was added in https://github.com/wojtekmach/req/commit/f7156a7f5e24dcdcf62240d221299c9f4f308a57 when the `@moduledoc` for `Req` depending on parsing the README.md. However that was subsequently removed so now the `@external_resource` line is only resulting in extraneous recompilation and can be safely removed.
> Remove @external_resource

- lib/req/steps.ex
Following the conversation here : https://github.com/wojtekmach/req/pull/154
It seems that the `URI.merge/2` algorithm just does what we want.
(Reminder: this was to support urls such as `//somehost/path/to` when following redirects)
> use URI.merge to derive the redirect URL from the current URL

- lib/req.ex
- lib/req/steps.ex
- test/req/steps_test.exs
This PR allows an optional callback function to be passed as an options which allow modification of the Finch request object before it is executed.
> `run_finch`: Add `:finch_request` option

- lib/req.ex
- lib/req/steps.ex
- test/req/steps_test.exs
Also, allows `false` to disable logging of retry messages.
> Allow customization of log level for retry messages

- lib/req/steps.ex
- test/req/steps_test.exs
According to the documentation it should be possible to pass a `:hostname` option to finch as part of `:connect_options`.
Passing the `:hostname` option resulted in an ArgumentError because `:hostname` was not part of the valid options MapSet.
This commit adds `:hostname` to the valid options MapSet.
> Fix "(ArgumentError) unknown option :hostname"

- lib/req.ex
- lib/req/steps.ex
Hi,
This is a nice library, thank you.
Here's a PR with the intent of avoiding bugs: Removing the automatic upgrading of `NaiveDateTime` to GMT.
In this case a `NaiveDateTime` is silently "upgraded" to be GMT even though we have no idea if that's true or not.
If a developer has a `NaiveDateTime` that the developer is sure is UTC, it is trivial to call `DateTime.from_naive!(naive, "Etc/UTC")`. However libraries shouldn't assume the UTC offset since it can lead to bugs. The reason that the `NaiveDateTime` type exists is for when we don't know the timezone. Libraries should not assume the time zone offset of `NaiveDateTime`.
This is consistent with the standard library where if you call `DateTime.from_iso8601("2023-04-18 06:16:28.609427")` you get an error because the offset is missing from …
> Avoid assuming NaiveDateTime is GMT

- lib/req.ex
- lib/req/response.ex
- lib/req/steps.ex
- test/req/response_test.exs
- test/req/steps_test.exs
Hi there! This is basically a proposal with code: Add a `:finch_exec_request` option to the default Finch adapter in order to enable custom plugins/steps to implement streaming response bodies.
[This recent ChatGPT streaming example](https://github.com/wojtekmach/mix_install_examples/pull/22) got me thinking about how the example could be implemented in Req. Finch provides support for streaming responses with `Finch.stream/5`, but the `run_finch` adapter always calls `Finch.request/3`. One could create their own `run_finch_stream` adapter, but they would be duplicating quite a lot of effort. The idea of this proposal is that an optional `:finch_exec_request` function would be provided with the Finch request, name, and options, and would return either a Req response or an exception.
Using …
> [Proposal] Allow `:finch_request` to perform the underlying request

- README.md
Currently the link to `Req.new/1` in the README points to`https://hexdocs.pm/req/Req.html#get!/2`:
This PR is to fix the link reference so people can go to the correct page in HexDocs.
> Fix autolink reference for `Req.new/1` in README

- lib/req/steps.ex
- test/req/steps_test.exs
I found a situation today where we have params which we want to record unencoded to opentelemetry attributes but results in a path which is not URI encoded. This update will encode the path after application to the template so that the params don't need to be encoded by the user.
> Encode path params after applying

- CHANGELOG.md
- lib/req.ex
- lib/req/request.ex
- lib/req/steps.ex
Making internal representation private gives us room to manoeuvre in the future. For example, changing options to keywords list would allow keeping duplicate keys and these could be handled on a per-step basis, for example `put_params/1` step could _merge_ params when someone wrote `Req.new(params: [a: 1]) |> Req.update(params: [b: 2])` as opposed to currently taking the _latter_ (#200).
Another reason is, with maps developers might be tempted to write:
def my_step(req) when req.options.foo == true
which is perfectly fine. However, changing this to:
def my_step(req) when req.options.foo == true or req.method == :get
is a bug. This code would work if `req.options` contains `:foo` key but if it doesn't, the ` or req.method == :get` is never executed. Changing the order would fix the …
> Make `request.options` & `request.registered_options` internals private

- lib/req/steps.ex
- test/req/steps_test.exs
When decompressing, the `content-length` is left unchanged. As a consequence, it's no longer matches the body's length, and could confuse other steps or users.
This PR automatically sets `content-length` after decompression.
It could be discussed if it's worth adding it if it wasn't there in the first place. I'd argue it cannot hurt, and proxies routinely do this. Not only it doesn't hurt, but it can help a client know when the response has been fully recieved (should `Req` be used in a reverse-proxy one day) especially when using multiplexing (`Connection: keep-alive`).
Not sure if we should update the documentation to notice users about these changes.
> Set content-length when decompressing

- lib/req/response.ex
- lib/req/steps.ex
- test/req/steps_test.exs
As noted here https://github.com/wojtekmach/req/pull/203#issuecomment-1693289313, I made the agreed changes except for the one changing the behavior of the function when it returns `true`. That part I left as it was i.e. it will have delay fetched from the `retry-after` header only if the status code is 429. Again, my advice is not to force users to double check their existing code base when switching to the 2-arity function.
> switch to `:retry` 2-arity fun, add support for {:delay, milliseconds}

- CHANGELOG.md
- lib/req.ex
- lib/req/request.ex
- lib/req/response.ex
- lib/req/steps.ex
- mix.exs
- test/req/httpc_test.exs
- test/req/request_test.exs
- test/req/steps_test.exs
- test/req_test.exs
> `Req.Request`, `Req.Response`: Change headers to be maps

- .github/workflows/ci.yml
- CHANGELOG.md
- lib/req/response.ex
- lib/req/steps.ex
- mix.exs
- test/req/steps_test.exs
> Add `%Req.Response{}.trailers` field

- CHANGELOG.md
- lib/req/steps.ex
- test/req/steps_test.exs
Previously we were changing to GET for all 3xx except 307 and 308
Closes #235.
> `redirect`: Change POST to GET on HTTP 301..303

- lib/req.ex
- lib/req/steps.ex
- test/req/steps_test.exs
Resolve #251 
This adds the `:finch_private` option which will allow adding private metadata to the Finch request when built so it travels through Req's finch adapter. This is helpful for putting custom metadata in for handling in `:telemetry` event handlers.
> Add `:finch_private` option to put into Finch.Request

- lib/req.ex
As discussed here: 
https://github.com/wojtekmach/req/pull/224#issuecomment-1705159795
As a couple of `iex` tests learned my that `headers: %{"key" => "value"}` maps are also accepted and merged correctly (i.e. no need to explicitly wrap `"value"` in `["value"`]), using maps in the examples felt like an improvement, as they are closer to the `%Req.Request{}` typespec.
> Use maps for request header examples

- lib/req/request.ex
The typespec for `put_header/3` needs to be different between the two versions, since the new version also allows lists of binaries.
> Fix typespec for `put_header`

- lib/req/response.ex
- test/req/response_test.exs
I went through the doc during a work task and found that the `put_header` doc was still referencing "non-map" (pre 0.4) headers format.
Instead of just fixing it, I preferred to understand why the test was not failing in the first place, discovered that it was disabled, re-enabled it and fixed it.
Unsure if I missed something (re: `Req.MixProject.legacy_headers_as_lists?` in particular), or other motivations which may have lead to that specific doctest being disabled, so feel free to adapt!
> Fix incorrect `put_header` doctest (& re-enable the doctest)

- lib/req/steps.ex
This change uses `put_header/3` instead of `put_new_header/3` in the `Req` auth step. This allows the auth step to be reused later in the pipeline to replace the authorization header e.g. when credentials are expired and need to be refreshed.
Closes #297.
> fix: Use `put_header/3` instead of `put_new_header/3` in auth step.

- lib/req/steps.ex
- test/req/steps_test.exs
Fixes #291
Remote may return multiple content-types in a list.  However, match is only present for a single entry.  For now, select the first content-type in the list as the format.
> Handle content-type when there is more than one in the header list

- lib/req/test.ex
Clarifies the second example should be `config/test.exs`
> Fix typo in Req.Test docs

- lib/req/steps.ex
Formatting, plus added a link to `MIME.extensions/1` cause I had to go read the source to make sure this is what this step was doing.
cc @wojtekmach
> Add some info to `Req.Steps.decode_body/1` docs

- lib/req/steps.ex
- lib/req/too_many_redirects_error.ex
- test/req/steps_test.exs
Currently, the included `redirect` step raises an exception with a message when the maximum number of redirects is reached.  This change modifies the existing raise behavior to instead use the halt and return exception behavior used by other steps in the pipeline.
> Use Req.Request.halt/1 and return redirect exception instead of raising on "too many redirects"

- lib/req/test.ex
- test/req/test_test.exs
@wojtekmach I think this makes sense in the optics of tests and stubs. I have found myself doing a lot of `send(test_pid, ...)` to ensure that everything gets called and in the right order. This helps a lot with that, since it introduces ordering. We'd need the usual `verify` suspects, but I'll only spend time on those if you think this change is good 😄
> Add Req.Test.expect/3

- lib/req/steps.ex
- test/req/steps_test.exs
When the redirect step is presented with a response where no `Location` header is specified, a MatchError is thrown from: https://github.com/wojtekmach/req/blob/3852d7e1d0861e7c4a6ae176dba2224d1aaf786e/lib/req/steps.ex#L1990
This patch introduces a function to retrieve and coalesce the `Location` header, avoiding a match error and respecting RFC 2616 section 10.3 (redirects).
Fixes #330
> Fix MatchError during redirect with no location header

- lib/req/decompress_error.ex
- lib/req/steps.ex
- test/req/steps_test.exs
See #335 - Improve decompression failure error handling by returning Req.DecompressError
This PR adds a new error type (below) to handle decompression failures.
```elixir
%Req.DecompressError{
format: :gzip | :br | :zstd,
data: binary()
}
```
> Handle decompress_body/1 errors by returning Req.DecompressError

- lib/req/steps.ex
Found a minor mistake in the `put_aws_sigv4` documentation example. Thanks for the great project!
> Fixed documentation example for put_aws_sigv4

- lib/req/test.ex
- test/req/test_test.exs
@wojtekmach I’m not sure how you'll feel about this but to me this is step number 1 towards what we talked about. To have complete mock functionality, we'll probably need this. It's really low maintenance (Mox has been like this for the past 7-8 years?) and if we sort of vendor its code (modified to fit this) and nimble_ownership's code you'll have top-notch testing support, IMO. Thoughts?
> Add more Mox-like functions to Req.Test

- lib/req/request.ex
> Add some types to Req.Request

- lib/req/utils.ex
- test/req/utils_test.exs
When using Req and the `aws_sigv4` option, AWS Bedrock endpoints that contain a `:` in the path (e.g. `https://bedrock-runtime.us-west-2.amazonaws.com/model/anthropic.claude-3-sonnet-20240229-v1:0/invoke`) fail signature verification. Model names without `:` are able to pass signature verification and run, but any with a colon fail signature verification.
```
The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
```
I tracked it down to a path encoding issue inside `aws_sigv4_headers`. According to the [docs](https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html), the path should be mostly URI encoded. With the changes in this PR signature …
> CanonicalURI encoding issue in aws_sigv4

- lib/req/utils.ex
tl;dr - Req library doesn't derive the aws v4 signature properly while using custom headers. 
AWS signature v4 computation requires the `canonical_headers` to be alphabetically sorted - reference: https://docs.aws.amazon.com/IAM/latest/UserGuide/create-signed-request.html#create-canonical-request
Here is a detailed example:
```
defmodule ElixirHelloworldTest do
use ExUnit.Case
doctest ElixirHelloworld
test "greets the world" do
assert ElixirHelloworld.hello() == :world
IO.puts(Req.new(
aws_sigv4: [
access_key_id: "<>",
secret_access_key: "<>",
region: "auto",
service: :s3
],
url: "https://silent-voice-3347.fly.storage.tigris.dev",
params: %{
"list-type" => "2"
},
headers: %{
"X-Tigris-Query" => "`Content-Length` > 6"
}
)
|> Req.run())
end
end
```
As you can see there is a custom header …
> fix: Fix the aws signature v4 computation with custom headers

- lib/req/request.ex
The code example on this function is this:
```elixir
|> Req.Request.register_options([:foo])
```
Which shows a list of atoms being passed in, so I don't think `keyword()` is the right spec.
> Fix spec on register_options/2

- lib/req/test.ex
- test/req/test_test.exs
When putting Req.Test into shared mode, I was getting a CaseClauseError when trying to access plugs.
```elixir
** (CaseClauseError) no case clause matching: {:shared_owner, #PID<0.681.0>}
(req 0.5.1) lib/req/test.ex:365: Req.Test.__fetch_plug__/1
(req 0.5.1) lib/req/test.ex:621: Req.Test.call/2
(req 0.5.1) lib/req/steps.ex:1268: Req.Steps.run_plug/1
(req 0.5.1) lib/req/request.ex:1101: Req.Request.run_request/1
(req 0.5.1) lib/req/request.ex:1045: Req.Request.run/1
```
This PR adds a new case that handles the {:shared_owner, owner} tuple returned by Req.Test.Ownership.fetch_owner/4 when in shared mode.
> handle {:shared_owner, owner} in __fetch_plug__

- lib/req/finch.ex
- test/req/finch_test.exs
Hi, 
I was unable to override the finch instance and traced it back to commit https://github.com/wojtekmach/req/commit/7ee7fd8effe22fd59d87723c86ba652d4a0c6a0e which removed the functionality.
This PR should revert that + adds a test to check that the `:finch` option can be used.
> use `:finch` value to override finch instance

- lib/req/utils.ex
- test/req/utils_test.exs
Presigned URLs should remain valid across custom endpoint ports (e.g., 9000 instead of the standard 80 or 443) by including port numbers in the host header.
For related discussions in other repositories, see:
- https://github.com/awslabs/aws-sdk-kotlin/issues/1177
- https://github.com/minio/minio/issues/11743
- https://github.com/aws/aws-sdk-js-v3/pull/3897
> fix: include custom ports in aws_sigv4_* functions

- lib/req/finch.ex
If the option `legacy_headers_as_lists` is set to `true` and running the following code will return an error
```elixir
Req.get!("https://github.com/wojtekmach/req/archive/refs/tags/v0.5.5.zip", into: File.stream!("test.tar.tz"))
```
```
** (BadMapError) expected a map, got: []
(stdlib 5.2.1) :maps.merge([], %{"cache-control" => ["max-age=0, private"], "content-length" => ["0"], "content-security-policy" => ["default-src 'none'; base-uri 'self'; child-src github.com/assets-cdn/worker/ github.com/webpack/ github.com/assets/ gist.github.com/assets-cdn/worker/; connect-src 'self' uploads.github.com www.githubstatus.com collector.github.com raw.githubusercontent.com api.github.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com …
```
> Check legacy headers when streaming headers

- lib/req/utils.ex
- test/req/utils_test.exs
I encountered a `SignatureDoesNotMatch` when the object key contains characters that need to be escaped, such as spaces or CJK characters.
The `path` has been encoded at 168L, so we just update the `url` before returning.
https://github.com/wojtekmach/req/blob/a3c48b845119069909e9197cd53264782513b4b4/lib/req/utils.ex#L168
> fix: encode path in url for aws_sigv4_url/1

- README.md
Hi Woytek,
Following up on our discussion yesterday, here's a PR to start a list of related packages in the README of Req. I hope this helps people find interesting packages, and helps interesting packages be found.
I've moved the existing list of links down to this section.
Let me know if you'd like me to make any changes or have any other feedback.
Derek
> Add Related Packages section and list `curl_req`

- lib/req.ex
- lib/req/finch.ex
- lib/req/request.ex
- lib/req/steps.ex
- test/req/finch_test.exs
- test/req/steps_test.exs
Currently when we pass `into: collectable`, the body is streamed into the collectable, regardless the status. This can be problematics for collectables with side effects. For example, I imagine a common use case may be `into: File.stream!(path)` to download a file, and in case of an error, we would save error message body instead.
There is one concern, that I'm not sure how to solve, hence a draft (details in separate comment).
> Ignore :into collectable for non-200 responses

- lib/req.ex
- lib/req/finch.ex
- lib/req/steps.ex
In some cases, a long-running app may want to make requests to arbitrary URLs (e.g. specified by the user). By default finch would start a separate pool for each host and keep it indefinitely, but this can be configured with the `:pool_max_idle_time` option.
Initially I wanted to just use a custom finch pool and do `Req.new(finch: TransientFinchPool)`, however we also use `:connect_options`, and these cannot be used together. Hence, I'm proposing to add the Finch pool option. Thoughts?
> Add option to configure Finch pool :pool_max_idle_time

- lib/req/finch.ex
> Add TODO for Finch v0.20

- lib/req/utils.ex
- test/req/utils_test.exs
S3-compatible APIs support additional headers for certain behaviors. For example, my team wants to create presigned urls for uploading files from the client. To ensure integrity of uploads and keep track of storage consumption by our end users, we want to enforce the uploaded file is the size reported by the client. This can be accomplished using the `content-length` header.
S3 supports `content-length-range` which I see is used by req_s3 `presign_form/1`. However, we're using Cloudflare R2 via their S3-compatible API and it appears that value is not supported but the `content-length` header is. Additionally, we want the exact size to be enforced, not a range or max.
This PR supports arbitrary headers passed to `Req.Utils.aws_sigv4_url/1`. I wasn't entirely sure where this belongs as …
> Support custom headers in aws_sigv4_url/1

- lib/req/steps.ex
- lib/req/utils.ex
- test/req/utils_test.exs
> Support any enumerable in mutlipart

- README.md
I just released HttpCookie v0.7.0, with sane defaults for cookie length and count limits, and an easy to use Req plugin.
> Link to HttpCookie

- lib/req/steps.ex
- lib/req/utils.ex
- test/req/steps_test.exs
- test/req/utils_test.exs
Closes #456 
- adds `:content_length` (maybe rename to `:size`?)
- the new option IS required when value type is `Enumerable`
- no validation :( users can craft requests with incorrect content-length header
> Support any enumerable in mutlipart 2

- lib/req/test.ex
- test/req/test_test.exs
This commit fixes
```elixir
Req.Test.set_req_test_to_shared()
Req.Test.expect(MyApp.Weather, fn conn ->
Req.Test.json(conn, %{"celsius" => 25555.0})
end)
assert {:ok, %Req.Response{}} == Reqrepro.hello()
```
which would produce
```
** (CaseClauseError) no case clause matching: %{expectations: [#Function<0.11329399/1 in ReqreproTest."test test"/1>]}
code: assert {:ok, %Req.Response{}} == Reqrepro.hello()
stacktrace:
(req 0.5.8) lib/req/test.ex:390: Req.Test.__fetch_plug__/1
(req 0.5.8) lib/req/test.ex:632: Req.Test.call/2
(req 0.5.8) lib/req/steps.ex:964: Req.Steps.run_plug/1
(req 0.5.8) lib/req/request.ex:1106: Req.Request.run_request/1
(req 0.5.8) lib/req/request.ex:1050: Req.Request.run/1
```
> Fix Test.expect in shared mode

- lib/req.ex
- lib/req/test.ex
Hi @wojtekmach 👋
- fixes a small example to look more natural
- document the options from this [step](https://hexdocs.pm/req/Req.Steps.html#handle_http_errors/1) upstream
I also had a small question regarding [`default_options`](https://hexdocs.pm/req/Req.html#default_options/0): I noticed based on the implementation that it should be possible to set this from a config, but this is undocumented behavior so I didn't want to rely on it. Do you think this could this be officially documented?
(might avoid it anyway, I could totally understand the argument that such a global would be a smell, but given that the option exists and that it could streamline things in some non-library projects I figured I'd ask).
> Minor improvements to the documentation

- lib/req/utils.ex
- test/req/utils_test.exs
Similar to https://github.com/wojtekmach/req/pull/443, S3-compatible APIs support additional query parameters for certain behaviors. One example is to set the response content disposition for file downloads, as motivated by https://github.com/wojtekmach/req_s3/issues/8.
This PR supports arbitrary query parameters passed to `Req.Utils.aws_sigv4_url/1`.
> Support custom query params in Req.Utils.aws_sigv4_url/1

- .github/workflows/ci.yml
- lib/req/utils.ex
- mix.exs
As discussed.
https://hexdocs.pm/elixir/main/Stream.html#transform/5
A couple of other small changes:
- like [`:zlib.gzip`](https://github.com/erlang/otp/blob/OTP-27.3/erts/preloaded/src/zlib.erl#L757-L766), only `close` is called in the `after` block, `deflateEnd` is in the last block (I'm not sure if it is actually safer to prevent leaks, but it feels better to be be consistent with the original implementation)
- when checking the return of `deflate`, it can return a lot of `[]` -> I didn't benchmark but it feels cleaner to just not emit these - also see https://github.com/elixir-lang/elixir/pull/13793 for context
> Refactor stream_gzip to use Stream.transform/5

- lib/req/utils.ex
- test/req/steps_test.exs
- test/req/utils_test.exs
Currently on form multipart requests, an unnecessary extra CR/LF gets inserted after the request headers. The fix is to change this encoding pattern:
[crlf part] [crlf part] [crlf footer]
To this pattern:
[part crlf] [part crlf] [footer]
> Fix leading newline before form multipart body

- lib/req/steps.ex
- lib/req/test.ex
- lib/req/test/adapter.ex
- test/req/adapter_test.exs
- test/req/test/adapter_test.exs
In commit c17cd20 using `run_plug` was modified to ensure that the body was read. This was much more convenient for tests that assert on body_params for JSON or file uploads, however it could break existing tests that were using `read_body` directly.
This commit adds a custom adapter that supports calling read_body, however it warns the user. The body is cached in the custom adapter, and re-populates the body when reading, to ensure that the existing `read_body` options work.
In a future commit, we should add the ability to opt-out of the automatic parsing, which would inform the custom adapter to simply delegate to the `Plug.Adapters.Test.Conn` adapter.
> Use a custom adapter for transitioning to automatic body reads

- lib/req/steps.ex
- test/req/steps_test.exs
Fixes #488 
This pull request enhances URI encoding in the `Req` library by ensuring reserved characters are properly escaped and adds corresponding test cases to verify this behavior.
* [`lib/req/steps.ex`](diffhunk://#diff-07dc6fd4ec95415d610a3e3ddf9374540d6d64d02eaf42df7a233d6f05b32cc1L547-R547): Updated the `URI.encode` call to use the `URI.char_unreserved?/1` function, ensuring proper handling of reserved characters during URI encoding.
* [`test/req/steps_test.exs`](diffhunk://#diff-dc476e4c9226d38862002c18df4835a1d51d98448df84548cd4e144fae0ec2e9R332-R346): Added a new test, `put_path_params properly escapes reserved characters`, to validate that reserved characters (e.g., `#`) are correctly escaped in both default and curly path parameter styles.
> fix: fully encode path_params even with reserved characters
