wojtekmach/req

- lib/req.ex
- mix.exs
- test/req_test.exs
> Req.put!/3 and Req.delete!/2

- lib/req/request.ex
> Ensure get_private/put_private have atom keys

- lib/req.ex
> Rename `max_attempts` to `max_retries`

- lib/req.ex
This allows for steps to be anonymous functions or an MFA tuple.
Closes #16
> Use MFA for default steps

- lib/req/steps.ex
- test/req/steps_test.exs
> change method to get on 301..303 redirects

- lib/req/steps.ex
- test/req/steps_test.exs
> support bearer auth

- lib/req.ex
- lib/req/steps.ex
- test/req/steps_test.exs
> Add `:output` step

- lib/req.ex
- lib/req/steps.ex
- test/req/steps_test.exs
> `follow_redirects`: Add `:max_redirects` option

- lib/req.ex
- lib/req/steps.ex
- test/req/steps_test.exs
> do not trust different port, scheme

- lib/req.ex
- lib/req/request.ex
- lib/req/steps.ex
- test/req/request_test.exs
It implements the same behaviour as [`Plug.Conn.put_req_header/3`](https://hexdocs.pm/plug/Plug.Conn.html#put_req_header/3) does.
> Add `Req.Request.put_header/3` function

- CHANGELOG.md
- lib/req/steps.ex
- test/req/steps_test.exs
Closes #43.
I don't love how this is tested, so if you know of a better approach I am more than happy to implement it.
> Handle 429 Retry-After header

- .github/workflows/ci.yml
- CHANGELOG.md
- lib/req.ex
- lib/req/steps.ex
- mix.exs
- test/req/steps_test.exs
> allow `:retry_delay` to be a `{&fun/1, initial}`

- lib/req/steps.ex
> `put_base_url`: Use URI.merge/2

- lib/req/steps.ex
- test/req/steps_test.exs
> Set Accept header in JSON requests

- lib/req.ex
> merge adapter passed to Req.request/2

- lib/req/steps.ex
- test/req/steps_test.exs
Addressing issue https://github.com/wojtekmach/req/issues/122
Stole idea from Tesla: https://github.com/elixir-tesla/tesla/blob/master/lib/tesla/middleware/core.ex#L33-L52
> `base_url` fix

- lib/req/response.ex
Follow up on https://github.com/wojtekmach/req/pull/145#issuecomment-1279993636
PS: I've sent you a DM on twitter  👍
> Adapt Req.Response.json/3 to not override content type

- lib/req.ex
- lib/req/steps.ex
- test/req/steps_test.exs
Howdy @wojtekmach how is it going?
Here is the PR for issue #178.
Let me know if you see any issues.
Cheers.
> `follow_redirects`: Add `:redirect_log_level`

- lib/req/steps.ex
- test/req/steps_test.exs
> fix 307/308 redirect behavior

- lib/req/response.ex
Hi! 👋
I came across this library on Twitter, started using it and wanted to see if I could start contributing somehow.
This seemed like the only missing part for #194 so I wanted to create a PR, unless I misunderstood something. :)
> Raise when trying to fetch response header with multiple values

- README.md
Great overview by Req's creator.
> Add screencast link to README.md

- CHANGELOG.md
- lib/req.ex
- lib/req/request.ex
- lib/req/steps.ex
- test/req/steps_test.exs
> Rename `follow_redirects` to `redirect`

- lib/req.ex
The documentation for retry got out of sync with the implementation. I copied the docs from `steps.ex` to update them.
> Update retry documentation

- README.md
Make it easier to quickly get useful stats about the library
Preview:
> Add standard badges to README.md

- lib/req.ex
- lib/req/steps.ex
- test/req/integration_test.exs
- test/req/steps_test.exs
> New step: `checksum`

- mix.exs
> Relax nimble_owernship requirement

- lib/req/test.ex
Just a bunch of docs to clarify stuff, plus specs.
> Improve docs for Req.Test and add specs

- lib/req/test.ex
- test/req/test_test.exs
Last touch for `Req.Test`. I think this is nice because at least it completes the mock/stub interface. After this, I think we're done with `Req.Test` 🙃
> Add verify* functions to Req.Test

- lib/req/test.ex
> Add :since docs to some Req.Test stuff

- lib/req.ex
- lib/req/request.ex
- lib/req/steps.ex
- lib/req/test.ex
- mix.exs
- test/req/test_test.exs
> Update `Req.Test` docs

- lib/req/request.ex
Tiny docs improvements + specs.
> Improve docs for Req.Request.halt/2

- lib/req.ex
- lib/req/steps.ex
- lib/req/test.ex
- test/req/steps_test.exs
Closes https://github.com/wojtekmach/req/issues/369
> Default :retry_log_level to :warning

- README.md
Maybe it's just me preferring the badges but the docs link felt a bit lost on its own and it seems better with the badges up top.
Feel free to close if you disagree :green_heart:
> Make docs a badge link

- README.md
> Update Telsa URL

- lib/req.ex
Hey there, I've added an example of a proxy request from our [discussion](https://elixirforum.com/t/making-a-req-request-with-proxy/65771/4). I hope this is up to par.
More than happy to fix any issues or errors!
> Adds an example of a Proxy request

- README.md
https://github.com/leandrocp/req_embed
> Add related project req_embed

- README.md
This was annoying for me, hopefully it helps someone else
> chore: instructions for compiling brotli
